npc:
  defaultRole: deepseek-v4-pro
  roles:
    - name: hy3
      avatar:
        src: /assets/cbc.png
      slogan: 准备好改变您的开发方式了吗？ --省钱
      prompt: 开干吧各位  
    - name: deepseek-v4-pro
      avatar:
        src: /assets/cbc.png
      slogan: 准备好改变您的开发方式了吗？--省钱+聪明
      prompt: 开干吧各位
    - name: deepseek-v4-flash
      avatar:
        src: /assets/cbc.png
      slogan: 准备好改变您的开发方式了吗？--省钱+呆
      prompt: 开干吧各位
    - name: glm-5.2
      avatar:
        src: /assets/cbc.png
      slogan: 准备好改变您的开发方式了吗？ --very 贵
      prompt: 开干吧各位
    - name: glm-5.1
      avatar:
        src: /assets/cbc.png
      slogan: 准备好改变您的开发方式了吗？ --very 贵
      prompt: 开干吧各位
    - name: glm-5.0-turbo
      avatar:
        src: /assets/cbc.png
      slogan: 准备好改变您的开发方式了吗？--贵
      prompt: 开干吧各位


