.1m-high: &1m-high
  issue.comment@npc:
    - docker:
        image: cnbcool/default-npc:latest
      stages:
      - name: run with npc
        type: npc:go
        options:
          model: ${CNB_NPC_NAME}
          contextWindow: 1m
          thinkingLevel: high

  pull_request.comment@npc:
    - docker:
        image: cnbcool/default-npc:latest
      stages:
      - name: run with npc
        type: npc:go
        options:
          model: ${CNB_NPC_NAME}
          contextWindow: 1m
          thinkingLevel: high

deepseek-v4-pro: *1m-high
deepseek-v4-flash: *1m-high
# deepseek-v4-flash-vision-exp: *1m-high

glm-5.3: *1m-high
glm-5.3-flash: *1m-high
glm-5.2: *1m-high
kimi-k3: *1m-high

hy4-preview: *1m-high

main:
  pull_request:
    - stages:
        - name: commitlint
          image: cnbcool/commitlint

  pull_request.mergeable:
    - stages:
        - name: automerge
          type: git:auto-merge
          options:
            mergeType: squash
            removeSourceBranch: true
