.1m: &1m
  issue.comment@npc:
    - docker:
        image: cnbcool/default-npc:latest
      stages:
      - name: set model
        script: |
          if [ "$CNB_NPC_NAME" = "hy4-preview" ]; then
            echo "##[set-output NPC_THINKING=high]"
          elif [ "$CNB_NPC_NAME" = "deepseek-v4-flash" ] || [ "$CNB_NPC_NAME" = "deepseek-v4-flash-version" ] || [ "$CNB_NPC_NAME" = "deepseek-v4.1-flash" ]; then
            echo "##[set-output NPC_THINKING=off]"
          else
            echo "##[set-output NPC_THINKING=medium]"
          fi
          if [ "$CNB_NPC_NAME" = "deepseek-v4-flash-version" ] || [ "$CNB_NPC_NAME" = "deepseek-v4.1-flash" ] || [ "$CNB_NPC_NAME" = "glm-5.3-flash" ]; then
            echo "##[set-output NPC_SUPPORT_IMAGE=true]"
          else
            echo "##[set-output NPC_SUPPORT_IMAGE=false]"
          fi
        exports:
          NPC_THINKING: NPC_THINKING
          NPC_SUPPORT_IMAGE: NPC_SUPPORT_IMAGE
      - name: run with npc
        type: npc:go
        options:
          model: ${CNB_NPC_NAME}
          contextWindow: 1m
          thinkingLevel: $NPC_THINKING
          supportImage: $NPC_SUPPORT_IMAGE

  pull_request.comment@npc:
    - docker:
        image: cnbcool/default-npc:latest
      stages:
      - name: set model
        script: |
          if [ "$CNB_NPC_NAME" = "hy4-preview" ]; then
            echo "##[set-output NPC_THINKING=high]"
          elif [ "$CNB_NPC_NAME" = "deepseek-v4-flash" ] || [ "$CNB_NPC_NAME" = "deepseek-v4-flash-version" ] || [ "$CNB_NPC_NAME" = "deepseek-v4.1-flash" ]; then
            echo "##[set-output NPC_THINKING=off]"
          else
            echo "##[set-output NPC_THINKING=medium]"
          fi
          if [ "$CNB_NPC_NAME" = "deepseek-v4-flash-version" ] || [ "$CNB_NPC_NAME" = "deepseek-v4.1-flash" ] || [ "$CNB_NPC_NAME" = "glm-5.3-flash" ]; then
            echo "##[set-output NPC_SUPPORT_IMAGE=true]"
          else
            echo "##[set-output NPC_SUPPORT_IMAGE=false]"
          fi
        exports:
          NPC_THINKING: NPC_THINKING
          NPC_SUPPORT_IMAGE: NPC_SUPPORT_IMAGE
      - name: run with npc
        type: npc:go
        options:
          model: ${CNB_NPC_NAME}
          contextWindow: 1m
          thinkingLevel: $NPC_THINKING
          supportImage: $NPC_SUPPORT_IMAGE

hy4-preview: *1m

deepseek-v4-pro: *1m
deepseek-v4-flash: *1m
deepseek-v4-flash-version: *1m
deepseek-v4.1-flash: *1m
# deepseek-v4-flash-vision-exp: *1m

glm-5.3: *1m
glm-5.3-flash: *1m
glm-5.2: *1m
kimi-k3: *1m

main:
  pull_request:
    - stages:
        - name: commitlint
          image: cnbcool/commitlint

  pull_request.mergeable:
    - stages:
        - name: automerge
          type: git:auto-merge
          options:
            mergeType: squash
            removeSourceBranch: true
